name: example
description: Example app for reduced_bloc.
publish_to: 'none' 
version: 0.2.0+3

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 
    git:
      url: https://github.com/partmaster/reduced
      ref: v0.2.0
  reduced_bloc: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
