name: example
description: Example app for reduced_bloc.
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 
    path: ../../reduced
  reduced_bloc: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
